export const techStacks = [
    { name: "JavaScript" },
    { name: "Vite" },
    { name: "TypeScript" },
    { name: "Formik" },
    { name: "Yup" },
    { name: "React" },
    { name: "Redux" },
    { name: "Formik" },
    { name: "Next.js" },
    { name: "Material-UI" },
    { name: "CSS3" },
    { name: "Tailwind CSS" },
    { name: "HTML" },
    { name: "CSS" },
    { name: "SASS" },
    { name: "Daisy-UI" },
    { name: "HTML5" },
  ];
  
  export const reactFeatures = [
    { react: "High Order Component" },
    { react: "React Hooks" },
    { react: "React Router 6" },
    { react: "React Suspense" },
    { react: "Function Comp" },
    { react: "Custom Hooks" },
    { react: "Clean Code" },
    { react: "Responsive Design" },
    { react: "Performance Optimization" },
    { react: "Components" },
    { react: "List & Keys" },
    { react: "REST API" },
    { react: "RTK" },
    { react: "JSX" },
    { react: "Scaling React Apps" },
  ];